name: 'tauri'

on:
  push:
    branches:
      - main

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Download external assets
        run: |
          wget https://f.iroiro.party/static/inkydays-data.tar.gz
          tar -xzf inkydays-data.tar.gz
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: inkydays-data
          path: data/

  build:
    needs:
      - assets
    strategy:
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            target: 'aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            target: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
          - platform: 'windows-latest'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install frontend dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true
      - name: Download asset artifacts
        uses: actions/download-artifact@v4
        with:
          name: inkydays-data
          path: data/
      - name: Build tauri app
        if: matrix.platform != 'macos-latest'
        run: |
          pnpm tauri build
      - name: Build tauri app (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          pnpm tauri build --target ${{ matrix.target }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform == 'macos-latest' && matrix.target || matrix.platform }}
          path: |
            ./src-tauri/target/release/*inkydays*
            ./src-tauri/target/**/*ink-tools*.app
            ./src-tauri/target/**/*ink-tools*.msi

